openapi: 3.0.0
info:
  title: Notification API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /add-notifications:
    post:
      summary: Add notifications for a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: The user's email address
                  example: email@example.com
                notifications:
                  type: array
                  description: The list of notifications to add
                  items:
                    type: string
                    example: Text #1
              required:
                - email
                - notifications
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                  notifications:
                    type: array
                    items:
                      $ref: '#/components/schemas/Notification'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
    security:
      - BearerAuth: []
  /messages:
    get:
      summary: Get all user notifications
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
    security:
      - BearerAuth: []
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        email:
          type: string
      required:
        - id
        - email
    Notification:
      type: object
      properties:
        id:
          type: integer
          format: int64
        text:
          type: string
      required:
        - id
        - text
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
